# Generated by Django 5.1.2 on 2024-10-20 22:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('established', models.DateField()),
                ('division', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('age_group', models.CharField(max_length=100)),
                ('training_ground_address', models.TextField()),
                ('contact_phone', models.CharField(max_length=15)),
                ('contact_email', models.EmailField(max_length=254)),
                ('twitter_link', models.URLField(blank=True, null=True)),
                ('youtube_embed_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
